### ISSUE TITLE
Control issue in Kibana

### ISSUE THREAD

**Issue by alkimozaygen** [The-Academic-Observatory/observatory-platform#346] opened 2021-01-25 03:02 UTC
Kibana space: 'oaebu-anu-press' and 'oaebu-ucl-press'
Dashboards: ANU Press - Google Books, ANU Press - JSTOR, ANU Press - OAPEN, UCL Press - Google Books, UCL Press - JSTOR, UCL Press - OAPEN

In Kibana when I create a ‘Title Select’ control in dashboards, titles can be seen in Google Analytics dashboards for both projects. However, for other dashboards which use other tables, in the 'Title select' dropdown menu only some words are showing. Titles can be seen in Discover. In Kibana index patterns page the 'Title' field is of type 'string', Searchable, and Aggregatable.

**Comment by alkimozaygen** [comment] 2021-01-26 12:42
Kibana space: 'oaebu-anu-press' and 'oaebu-ucl-press'
Dashboards: ANU Press - Google Analytics, ANU Press - JSTOR, ANU Press - OAPEN, UCL Press - Google Analytics, UCL Press - JSTOR, UCL Press - OAPEN

Another issue related to controls in Kibana is filtering maps. The title filters do not affect maps on the dashboards.

**Comment by rhosking** [comment] 2021-01-29 03:55
![image](https://user-images.githubusercontent.com/4916251/106229558-b0eb8f00-6252-11eb-972d-e64d3a94b2f8.png)

@alkimozaygen the setting above seems to be currently toggled off on the maps, I changed this on the 'Web Sessions - map' and that seemed to work. This should be the same fix for all other maps.

**Comment by rhosking** [comment] 2021-01-29 03:59
additionally, the initial issue is caused by the Title field being called different things throughout the indexes. 'Page_title', 'title', 'book_title' etc etc

I believe that whatever index and especially field used in the Title Select, will only work for other indexes which have a field on the exact same name

**Comment by bechandcock** [comment] 2021-01-29 05:24
> additionally, the initial issue is caused by the Title field being called different things throughout the indexes. 'Page_title', 'title', 'book_title' etc etc
> 
> I believe that whatever index and especially field used in the Title Select, will only work for other indexes which have a field on the exact same name. The underlying data in BigQuery all has different names for this field, so choosing a unified name will be the next step, as part of the general integration and aggregation workflows that are required

For sure, and this is why we have been pushing to get a basic schema standardised between data so that the data filters can all work. Having 4 seperate dashboards in a webpage is a workaround because we did not have the same names for data nor know how it was imported initially into ES so that we could edit it. While the full schema may be down the track, having these basic schema standardised is a block just now.

**Comment by rhosking** [comment] 2021-02-18 02:25
@alkimozaygen I believe this issue can now be marked as closed? there are a few things going on here. If there needs to be an issue open for the overall filtering limitation, perhaps open that separately if it doesn't already exist, but I think most of these items have been addressed?

**Comment by alkimozaygen** [comment] 2021-02-18 05:54
@rhosking the controls are working now. This issue can be marked now as closed.

**Comment by bechandcock** [comment] 2021-02-22 05:04
> . If there needs to be an issue open for the overall filtering limitation, perhaps open that separately if it doesn't already exist, but I think most of these items have been addressed?

The seperate issue which captures the cause of the filtering issue is #358

**Closed** 2021-02-28 22:02 UTC
Labels: OAeBU_Mellon, OAeBU_Mellon: Elasticsearch_Kibana, Observatory: Dashboard, Priority: High, Status: Blocked, Type: Bug
